### PR TITLE
added phillipgibson to members.yaml

### PR DESCRIPTION
**Pull request by phillipgibson**
## I want to join the Istio org!

- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://slack.istio.io)
- [X] I have written my company name or "Individual", if not affliated with a company, here: Microsoft
- [X] I have provided a link to at least one PR that I have successfully pushed to one of the Istio repos, here: 
 [istio.io - updated azure platform setup #13132](https://github.com/istio/istio.io/pull/13132)

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
Welcome!

**Comment by ericvn** [comment]
Welcome @phillipgibson. Was good to work with you on that PR.

**Comment by phillipgibson** [comment]
Whoops. I fat fingered the wrong pr #. It should be https://github.com/istio/istio.io/pull/13133 instead.

**Pull request merged**
