### PR TITLE
Migrate from Mergify/CircleCi to Tide/Prow

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by rlenferink** [comment]
When using Tide/Prow we need to have an [OWNERS file](https://go.k8s.io/owners) as well instead of the CODEOWNERS.

**Comment by geeknoid** [comment]
Nope, we figured out how to make Tide & Prow play nice with just plain CODEOWNERS.

**Comment by rlenferink** [comment]
A, that might be good as well. Is a difference between approvers and reviewers possible as well? Or is anyone mentioned in the CODEOWNERS files automatically able to approve?

**Comment by geeknoid** [comment]
There are two options:

- Anybody can post a comment against a pull request. So anybody can be a
reviewer

- Only folks listed in the CODEOWNERS file can approve and allow a PR to be
merged.

**Pull request merged**
