### PR TITLE
Add jaellio as security maintainer

### PR DESCRIPTION
**Pull request by jaellio**
Here are some PRs I've completed in this area ([30](https://github.com/search?q=org%3Aistio+author%3Ajaellio+is%3Apr+is%3Amerged&type=pullrequests) PRs currently merged in total):

- https://github.com/istio/istio/pull/50903
- https://github.com/istio/istio/pull/50365
- https://github.com/istio/istio/pull/48615
- https://github.com/istio/istio/pull/45632
- https://github.com/istio/api/pull/2888
- https://github.com/istio/istio/pull/45291
- https://github.com/istio/istio.io/pull/12680
- https://github.com/istio/istio/pull/43346
- https://github.com/istio/istio/pull/42980

Design docs/conversations:
- https://docs.google.com/document/d/1eVKo57JVQ8QGjqRkMYGHDraS_vANJf3tTUWqqbvcylQ/edit?usp=sharing
- https://docs.google.com/document/d/17L1g0LgmZP1vs-R1WJrwJvKKZwUUHIRgcDPXuTEH_qM/edit#heading=h.xw1gqgyqs5b
- https://github.com/istio/istio/issues/16585#issuecomment-1986542697

## I want to join the Istio org!

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)
- [x] I have written my company name or "Individual", if not affliated with a company, here: Microsoft
- [x] I have provided a link to at least one PR that I have successfully pushed to one of the Istio repos, here: [30 PRs Merged](https://github.com/search?q=org%3Aistio+author%3Ajaellio+is%3Apr+is%3Amerged&type=pullrequests)

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
This LGTM personally. Thanks for all the contributions!

FWIW @jaellio is already on the PSWG so this is just a slight expansion of responsibilities, not a first time maintainer`

**Review by kfaseela — APPROVED** [review]

**Comment by kfaseela** [comment]
Congratulations @jaellio

**Comment by linsun** [comment]
Congrats @jaellio - LGTM too!

**Comment by justinpettit** [comment]
Congratulations, @jaellio!

**Pull request merged**
