### PR TITLE
Add jtrbs as developers

### PR DESCRIPTION
**Pull request by jtrbs**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:
https://github.com/istio/istio/pull/26579

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Review by linsun — APPROVED** [review]

**Comment by jtrbs** [comment]
Hi @linsun , may I know if there is anything else I need to do to add myself into the org? Looks like after this PR and later https://github.com/istio/community/pull/448  was merged, my id has not been added into the org https://github.com/orgs/istio/people and I can not trigger tests in istio/istio repo. Thanks!

**Comment by howardjohn** [comment]
@jtrbs there is a pending invite for you. You need to accept it. Not sure how you do that - you probably got an email or can somehow find it in https://github.com/orgs/istio/people?

**Comment by jtrbs** [comment]
Hi @howardjohn, thanks for pointing that out! Found the email and accepted.

**Pull request merged**
