### PR TITLE
Update product security repo permissions

### PR DESCRIPTION
**Pull request by GregHanson**
Per TOC discussion on July 11, resolve permission issue with Product Security team so they are able to push patch branches to repos during security release

### CODE REVIEW

**Comment by GregHanson** [comment]
cc @howardjohn

**Comment by craigbox** [comment]
LGTM, /cc @linsun to confirm

**Review by howardjohn — APPROVED** [review]
LGTM, we should double check the set of users in this group if you didn't already

btw, do we need istio/istio as well?

**Comment by GregHanson** [comment]
@howardjohn following the Publishing steps from [here](https://github.com/istio-private/istio/issues/99), envoy, proxy, and istio are the ones listed.  `istio: write` is covered by maintainers group, but I do see other teams re-adding the permissions again on a team-by-team basis.  So I will add it

**Review by ericvn — APPROVED** [review]

**Comment by GregHanson** [comment]
/hold
reviewing PR today during Product Security WG call, will add final updates after meeting

**Comment by GregHanson** [comment]
Membership PR: https://github.com/istio/community/pull/772

**Comment by GregHanson** [comment]
Membership PR's have merged and all the required GitHub usernames have been added/removed.  Ready to merge

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
