### PR TITLE
Added nrjpoddar to TOC

### PR DESCRIPTION
**Pull request by nrjpoddar**
If you are joining the org, please fill out the template below:

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos:

### CODE REVIEW

**Comment by nrjpoddar** [comment]
> you have a bunch of other removes/adds - what are they for?

The build fails if I'm listed as a member but maintainer on the broader project. So to get notified on PRs, I upgraded myself to maintainer wherever I was a member.

May be there's another way of doing it?

**Comment by howardjohn** [comment]
The file is 1:1 mapping with github API, and github has a bad API (for this, at least). Working on improving it n https://github.com/istio/community/pull/322

**Comment by howardjohn** [comment]
which is broken by https://github.com/istio/community/pull/354

**Comment by nrjpoddar** [comment]
@rshriram LMK if you know a way to get around the issue I mentioned above.

**Comment by nrjpoddar** [comment]
Pinging @linsun @louiscryan

**Pull request merged**
