### PR TITLE
Add ilrudie as ztunnel maintainer

### PR DESCRIPTION
**Pull request by ilrudie**
I would like to be considered for ztunnel maintainer. I have around [50 PRs](https://github.com/search?q=org%3Aistio+author%3Ailrudie+is%3Apr+is%3Amerged&type=pullrequests) merged within the Istio org.

For ztunnel I have around [15 PRs merged](https://github.com/istio/ztunnel/pulls?q=is%3Apr+is%3Amerged+author%3Ailrudie+) including:

- implementing the initial connection manager to assert policy against open connections https://github.com/istio/ztunnel/pull/772
- improvements for the connection manager https://github.com/istio/ztunnel/pull/804/files
- implementing the service-addressed waypoint logic https://github.com/istio/ztunnel/pull/832
- improvements for service-addressed waypoint behavior https://github.com/istio/ztunnel/pull/873
- removing hair pinning https://github.com/istio/ztunnel/pull/913
- adding handling of Hostname enum variant for address lookup https://github.com/istio/ztunnel/pull/550
- improvements to the authorization proto to better align with the user-facing API https://github.com/istio/ztunnel/pull/501
- reducing the number of buffers used https://github.com/istio/ztunnel/pull/502

### CODE REVIEW

**Comment by linsun** [comment]
Thanks @ilrudie! I'll let our ztunnel maintainers to weigh in @istio/wg-networking-maintainers-ztunnel

**Comment by bleggett** [comment]
I'm biased obviously so if my vote doesn't count that's fine, but Ian has reviewed enough Rust code for me to have roughly zero qualms with him doing it here, +1 from me FWIW

**Review by hzxuzhonghu — COMMENTED** [review]
+1

**Review by kfaseela — APPROVED** [review]
Congratulations @ilrudie ! :)

**Comment by linsun** [comment]
Congratulations @ilrudie ! :)

**Comment by justinpettit** [comment]
Congratulations, @ilrudie!

**Comment by bleggett** [comment]
WOO!

**Pull request merged**
