### PR TITLE
Add new CLA info as we transition to LF CLA

### PR DESCRIPTION
**Pull request by craigbox**
Initial commit, building on https://github.com/kubernetes/community/blob/master/CLA.md

### CODE REVIEW

**Comment by craigbox** [comment]
@therealmitchconnors FYI only `cla/google` fired here; I guess this means you've only added the bot to `istio/istio`?

**Comment by therealmitchconnors** [comment]
The instructions for how to add the CNCF cla are out of date.  I have a ticket open to get access to the new system.  No ETA.

**Comment by ericvn** [comment]
I am seeing the new CLA, and Approved. Pretty easy process as noted here.

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by ericvn** [comment]
One issue I do see is the potential for cherry-picks to have an issue if the original author(s) don't accept the CNCF CLA where the original PR merged with a Google CLA.

**Comment by hzxuzhonghu** [comment]
This is very rare, if really have such case. Then someone can reimplement the patch for pre releases

**Comment by craigbox** [comment]
I am going to assume that no company will deliberately agree with Google's CLA and not the CNCF's, else the ecosystem would have lost them during the Kubernetes transition.  There may be some chasing but I am going to trust that people with active PRs are going to be engaged in the project, or at the least contactable.

**Pull request merged**
