### PR TITLE
Add Pawan-Bishnoi as member

### PR DESCRIPTION
**Pull request by Pawan-Bishnoi**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template. 

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:
Individual
Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

https://github.com/istio/istio/pull/43402

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
/ok-to-test

Welcome

**Review by zirain — APPROVED** [review]
Welcome!

/ok-to-test

**Comment by zirain** [comment]
> /hold

updated with a merged PR

**Comment by hzxuzhonghu** [comment]
nvm, the linked pr has been merged

**Pull request merged**
