### PR TITLE
Add nikita15p to istio org

### PR DESCRIPTION
**Pull request by nikita15p**
If you are joining the org, please fill out the template below:

- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

List your company name, or indicate Individual if you're not affiliated with a company:
nikita15p

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos:
https://github.com/istio/istio/pull/25999

### CODE REVIEW

**Comment by nikita15p** [comment]
Can u please review @bianpengyuan

**Comment by linsun** [comment]
@nikita15p Thanks for the interest!  We will approve once your istio/istio PR is merged.  Please give us a ping when istio/istio#25999 is merged.

**Comment by craigbox** [comment]
Hi Nikita,

Your example PR hasn't been merged yet - hopefully @ericvn can help there too.  My feedback is, there was no context on the PR as to why those lines were being removed.

**Comment by nikita15p** [comment]
@craigbox @linsus today morning my PR https://github.com/istio/istio/pull/25999 got merged. So can this PR be taken in now?

**Pull request merged**
