### PR TITLE
add aimuz to members

### PR DESCRIPTION
**Pull request by aimuz**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [ ] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

aimuz

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

https://github.com/istio/istio.io/pulls/aimuz

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]
Welcome! @aimuz

**Review by kfaseela — APPROVED** [review]

**Comment by craigbox** [comment]
Hi @aimuz,

Do you have a company affiliation?  You are listed as "not found" in CNCF.

**Comment by aimuz** [comment]
Hi @craigbox ,

Yes, I do. Do I need to register with CNCF? I don't seem to have operated it

**Comment by craigbox** [comment]
I can fix it if you just add it to this comment, or I can leave you as "independent" if you're not paid to work on Istio.

**Comment by aimuz** [comment]
Thank you. For now, please help me to keep "independent" and how I should proceed if there is a need to modify it in the future.

**Comment by zirain** [comment]
update your affiliation in https://github.com/cncf/gitdm

**Pull request merged**
