### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by nrjpoddar**
If you are joining the org, please fill out the template below:

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos:

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@douglas-reid @mandarjog currently all the members of P&T WG are listed as "members", I added myself as a maintainer as the builds fail if I'm a member in any WG but an admin for the project.

**Comment by douglas-reid** [comment]
@nrjpoddar shouldn't the rest of the members be maintainers?  What does it mean to be a maintainer of the maintainers group vs. a member?

**Comment by nrjpoddar** [comment]
> @nrjpoddar shouldn't the rest of the members be maintainers? What does it mean to be a maintainer of the maintainers group vs. a member?

I have no idea what's the difference as the current listed members were all maintainers. That's why I wanted to include you and Mandar on this PR. Let's create a follow-on PR if you think moving folks from "members" -> "maintainers" list is appropriate.

**Comment by howardjohn** [comment]
maintainer in this file == someone who is a member of the maintainer AND a
github admin. Which is super confusing, I am trying to make it easier to
use but blocked by me not having time to finish it

**Comment by douglas-reid** [comment]
ok. sounds good to me. @rshriram was asking me about this the other day.

**Pull request merged**
