### PR TITLE
Application for membership for jacob-delgado

### PR DESCRIPTION
**Pull request by jacob-delgado**
If you are joining the org, please fill out the template below:

- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

List your company name, or indicate Individual if you're not affiliated with a company:

Aspen Mesh

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos:

https://github.com/istio/istio/pull/20645/
https://github.com/istio/istio/pull/20671

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@linsun @louiscryan can we get this approved and merged? Jacob has merged around 5 PRs and without him being a member I cannot assign him issues. Thank you!

**Comment by nrjpoddar** [comment]
Thanks @ericvn!

**Comment by ericvn** [comment]
I know I've seen these approved and someone hadn't approved the testing so they stay stuck.  I'll at least kick the testing, but can't do the approval.

**Comment by nrjpoddar** [comment]
Thank you so much @linsun. Cheers!

**Pull request merged**
