### PR TITLE
Add shamsher31 to UX WG maintainers

### PR DESCRIPTION
**Pull request by shamsher31**
**As discussed in the UX WG meeting on  21 Oct 2020, Adding myself to UX WG maintainers.**

The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

> Red Hat

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

https://github.com/istio/istio/pull/24263
https://github.com/istio/istio/pull/27107

### CODE REVIEW

**Comment by shamsher31** [comment]
cc: @therealmitchconnors @esnible

**Review by knrc — APPROVED** [review]

**Comment by linsun** [comment]
@therealmitchconnors @esnible can you please record your approval here when you have time?   I assume you do.

**Comment by therealmitchconnors** [comment]
Whole-heartedly approved!  Welcome, Shamsher!

**Comment by shamsher31** [comment]
Thanks, Glad to be a part of UX WG.

**Pull request merged**
