### PR TITLE
update list of members in early disclosure list

### PR DESCRIPTION
**Pull request by rshriram**
This list is very much outdated. We can't keep updating this as more people join the list. But if people insist on having the list be public, lets make sure to have a process to keep this updated.

If you are joining the org, please fill out the template below:

- [ ] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [ ] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [ ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [ ] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [ ] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos:

### CODE REVIEW

**Comment by nrjpoddar** [comment]
I think we should keep it updated and product security WG should ensure that.

@fpesce @brian-avery wdyt?

**Comment by fpesce** [comment]
We probably need to keep the list public (and updated) for transparency purpose.

**Comment by rshriram** [comment]
okay updated the list. let me know if I missed someone

**Comment by nrjpoddar** [comment]
lgtm

**Pull request merged**
