### PR TITLE
Adding self to member list

### PR DESCRIPTION
**Pull request by jpapejr**
If you are joining the org, please fill out the template below:

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

List your company name, or indicate Individual if you're not affiliated with a company:
>IBM

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos:
https://github.com/istio/istio.io/pull/6648 (Merged)
https://github.com/istio/istio.io/pull/6864 (Merged)

### CODE REVIEW

**Comment by smawson** [comment]
Do you want to add yourself to the developers team as well?

**Comment by jpapejr** [comment]
Yep, will update..

**Pull request merged**
