### PR TITLE
Add pmerrison as a member

### PR DESCRIPTION
**Pull request by pmerrison**
As per conversation with Francis Zhou

The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company: Tetrate

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos: I do not have one, joining to help as a release manager

### CODE REVIEW

**Comment by kfaseela** [comment]
As per the [guidelines](https://github.com/istio/community/blob/master/ROLES.md#member), to be a member, one should push atleast one PR to any of the istio repos in last 6 months. I am not sure if we have any exceptions to release managers? @craigbox suggestions?

**Comment by ericvn** [comment]
@kfaseela Not on the steering committee, but I don't believe Release Managers get an exception, at least not noted in https://github.com/istio/istio/wiki/release-manager-expectations which has: `A member of the istio community and active for the last 3 months`

**Review by howardjohn — APPROVED** [review]
LGTM despite lack of a PR due to being release manager

**Comment by kfaseela** [comment]
Since TOC member approves, fine for me as well, then! Not approving to make sure one more steering member has a look and approves!

**Comment by linsun** [comment]
Can we wait till a PR merged from @pmerrison first?  Seems a reasonable ask before becoming a member for *anyone*.

**Comment by craigbox** [comment]
Or, put another way: does a release manager have to be a "project member"?  (e.g. is the lack of ability to start tests a blocker)

**Comment by howardjohn** [comment]
Release manager definitely needs to be a member. So they should either be both or neither

**Comment by ericvn** [comment]
Our tests do prevent one from being a RM without them being a member.

**Comment by ericvn** [comment]
> Or, put another way: does a release manager have to be a "project member"? (e.g. is the lack of ability to start tests a blocker)

I'm more concerned about the extra privileges RMs have over members (and maintainers) and we should make sure they understand the additional responsibility. Cutting back on the privileges would help that, but don't think we are that far yet.

**Comment by hzxuzhonghu** [comment]
The threshold of being a member is very low, I think it will be very soon to file a pr before this. So that we can make no exceptions for others too.

**Comment by pmerrison** [comment]
Sorry for the unnecessary controversy - here's a PR as required https://github.com/istio/bots/pull/615

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
