### PR TITLE
Add `thelinuxfoundation` as an admin

### PR DESCRIPTION
**Pull request by howardjohn**
This is needed for various CNCF operations. As proof this is 'safe',
Kubernetes does this as well, and CNCF recommends it for all projects I
think.

Requires https://github.com/istio/tools/pull/2868

### CODE REVIEW

**Review by justinpettit — APPROVED** [review]
LGTM

**Review by hzxuzhonghu — DISMISSED** [review]

**Comment by craigbox** [comment]
I love a self-verifying PR!

**Review by craigbox — APPROVED** [review]

**Pull request merged**
