### PR TITLE
Add self as a member

### PR DESCRIPTION
**Pull request by akshayjnambiar**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:
Google
Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:
istio/istio#42111
istio/istio#40948
istio/istio#40946
istio/istio#40053
istio/istio#39941
istio/istio#39840
istio/istio#39647

### CODE REVIEW

**Review by kebe7jun — APPROVED** [review]
Welcome!

**Comment by akshayjnambiar** [comment]
@kebe7jun i didn't notice the invitation until today and is expired now. What is the process to get a new invitation?

**Comment by kfaseela** [comment]
> @kebe7jun i didn't notice the invitation until today and is expired now. What is the process to get a new invitation?

Did you figure this out? Or still having issue?

**Comment by akshayjnambiar** [comment]
Still having the issue. Please help.

**Comment by kfaseela** [comment]
Looking at the last logs, we do have ```{"component":"unset","file":"/tmp/test-infra/prow/cmd/peribolos/main.go:1282","func":"main.configureTeamMembers.func1","level":"info","msg":"Waiting for akshayjnambiar to accept invitation to 3281404(Members)","severity":"info","time":"2022-11-30T09:53:53Z"}``` 

But cannot see any pending invites. If you don't get any new invite once any of the pending PRs get merged, will see how to retrigger one next week.

**Pull request merged**
