### PR TITLE
Create OWNERS

### PR DESCRIPTION
**Pull request by thisisnotapril**
beginning OWNERS for community repo

### CODE REVIEW

**Comment by geeknoid** [comment]
Are we going to setup a bot to make use of this file?

**Comment by linsun** [comment]
Without the bot, is the owners file of no use?  I think manual merge is fine for this repo as there is no test/wait concern.

**Comment by geeknoid** [comment]
The point of the OWNERS file is to drive the /lgtm & /approve process that
the bots control. Without the bots, the file doesn't do us much good.

Now, we're talking about potentially switching away from the bots towards
the built-in owner functionality that GitHub introduced a few months back.
So then we wouldn't need the bots.

**Comment by linsun** [comment]
I'd be up for the new built-in owner functionality from Git... I think bot is unnecessary for this repo. :). You should get some good sleep!

**Comment by thisisnotapril** [comment]
Thanks y'all; I'm more looking to have it documented how/who things get approved in this repo as we build out the governance, etc. So it's less about bots and more about a familiar documentation source for the community. Though I always welcome a good bot or two. 😄

**Pull request merged**
