### PR TITLE
Update co-lead of Extensions and Telemetry

### PR DESCRIPTION
**Pull request by zirain**
follow up: https://github.com/istio/community/pull/883#pullrequestreview-1214120904

### CODE REVIEW

**Review by kfaseela — APPROVED** [review]
Congratulations

**Comment by lei-tang** [comment]
Congrats, @zirain!

**Comment by kyessenov** [comment]
Awesome! Glad to see your work recognized.

**Comment by zirain** [comment]
thanks for your all!

**Pull request merged**
