### PR TITLE
Nominating myself back as a net/env maintainer

### PR DESCRIPTION
**Pull request by ymesika**
Following the background mentioned in #888 I'm also nominating myself as a networking / environment maintainer.

### CODE REVIEW

**Comment by ymesika** [comment]
cc @linsun

**Comment by kfaseela** [comment]
@ramaraochavali @hzxuzhonghu @howardjohn  approve?

**Comment by howardjohn** [comment]
From https://github.com/istio/community/blob/master/ROLES.md#requirements-3

> If a maintainer becomes inactive in the project for an extended period of time, the individual will transition to being an emeritus maintainer. Emeritus maintainers lose their ability to approve code contributions, but retain their voting rights for up to one year. After one year, emeritus maintainers revert back to being normal members with no voting rights.

I am quite happy to see you back in the community, but I am not sure that contributions from many years ago can be appropriately carried forward to present time. I think you can absolutely get to being a maintainer quickly, but it doesn't seem fair to others in the community to approve this when you do not meet the documented requirements to be a maintainer.

**Comment by linsun** [comment]
I recall we had discussion about this in TOC meetings lately, as part of cleaning up maintainers list for CNCF.  The consensus is emeritus maintainer can become maintainers anytime when he/she wants by submitting a PR to add back- @therealmitchconnors @louiscryan @ericvn @nrjpoddar do you recall?

**Comment by howardjohn** [comment]
I think its different if we _just_ marked them emeritus (hence "After one year, emeritus maintainers revert back to being normal members with no voting rights.") vs if we did 3 years ago

**Comment by linsun** [comment]
@ymesika this was discussed in TOC meeting, the consensus is to:

1. Must reapply after 1 month of activity.  activity needs to be performing maintainer activities, submit PRs & review PRs.
2. Obtain WG leads sponsorship for the WGs you are reapplying for maintainers.

Hope this helps!

**Pull request closed without merging**
