### PR TITLE
Add jtrbs as voter

### PR DESCRIPTION
**Pull request by jtrbs**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

I have added myself into developers before at https://github.com/istio/community/pull/419.

### CODE REVIEW

**Comment by craigbox** [comment]
Hi Tairan,

Welcome to Istio! Please [fill out the form](https://docs.google.com/forms/d/e/1FAIpQLSf9bqBtPas9Fn10o9ukLjQgfuUCTBnsbz2_H6kRQNIM6PIQxw/viewform) and Steering will check you qualify, which it looks like you do.  We can then approve this PR.

**Comment by jtrbs** [comment]
Hi @craigbox, thanks for replying! Since I have already merged a PR at https://github.com/istio/istio/pull/26579, do I still need to fill this `voter exception form`? I am referring to the following section within https://github.com/istio/community/blob/master/steering/elections/2020/README.md
```
Eligibility to vote is defined in the Steering Committee charter as either:

a project member who has had at least one Pull Request merged in the past 12 months, or
someone who has submitted the voting exception form and has been accepted by the steering committee as having standing in the community.
```

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
Actually, fair point; our counting stopped at 1 August iirc.  You qualify
by point 1.  I'll merge this.

**Comment by jtrbs** [comment]
@craigbox thanks a lot for your help!

**Pull request merged**
