### PR TITLE
add shonecyx as member

### PR DESCRIPTION
**Pull request by shonecyx**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:
eBay

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:
[istio/istio.io#36566](https://github.com/istio/istio/pull/36566)

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by shonecyx** [comment]
@hzxuzhonghu  Thanks for helping merge, I see the sync-org_community_postsubmit — Job failed, do you have any suggestion for that? 
https://prow.istio.io/view/gs/istio-prow/logs/sync-org_community_postsubmit/1476801756787642368

**Comment by ericvn** [comment]
The next job passed after we removed some failing users.

**Comment by shonecyx** [comment]
Thanks @ericvn for the fixing, do I need to rerun the org_community_postsubmit job or it will be reconciled later? Seems I'm still not the member.

**Comment by ericvn** [comment]
@shonecyx If I look in the logs of the last run: https://storage.googleapis.com/istio-prow/logs/sync-org_community_postsubmit/1478890935906471936/build-log.txt

I see:
```
{"component":"unset","file":"/tmp/test-infra/prow/cmd/peribolos/main.go:489","func":"main.configureOrgMembers.func1","level":"info","msg":"Waiting for shonecyx to accept invitation to istio","severity":"info","time":"2022-01-06T00:47:47Z"}
```
and
```
{"client":"github","component":"unset","file":"/tmp/test-infra/prow/github/client.go:761","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateTeamMembership(3281404, shonecyx, false)","severity":"info","time":"2022-01-06T01:18:58Z"}
{"component":"unset","file":"/tmp/test-infra/prow/cmd/peribolos/main.go:1301","func":"main.configureTeamMembers.func1","level":"info","msg":"Invited shonecyx to 3281404(Members) as a member","severity":"info","time":"2022-01-06T01:19:10Z"}
```
I don't see you on the invitee list or failed invite list however, so not sure what is going on. I'm relatively new to this group/member stuff so have to check with others to see if they can maybe shed some light on this.

**Comment by zirain** [comment]
@shonecyx seems you still not join the istio org. please confirm have your received an email with title `[GitHub] @istio-testing has invited you to join the @istio organization`?

**Comment by shonecyx** [comment]
@zirain  I found this invitation in my email(not the gmail) but unfortunately it was expired, how can I be re-invited?
```
@istio-testing has invited you to join the @istio organization on GitHub. Head over to https://github.com/istio to check out @istio’s profile.

This invitation will expire in 7 days
```

**Pull request merged**
