### PR TITLE
Add chaodaiG as developer

### PR DESCRIPTION
**Pull request by chaodaiG**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company: Google

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos: 
https://github.com/istio/test-infra/pull/2897

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Prs you committed are helpful

**Comment by smawson** [comment]
At least one PR in any Istio repo is a strong requirement, so yeah if you can get something in that would be good.

**Comment by chaodaiG** [comment]
OK will do. Any pointers would be appreciated

**Comment by chaodaiG** [comment]
Done. Please take another look

**Review by hzxuzhonghu — APPROVED** [review]

**Review by linsun — APPROVED** [review]

**Pull request merged**
