### PR TITLE
add saltbo to members

### PR DESCRIPTION
**Pull request by saltbo**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:
Individual

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:
https://github.com/istio/istio.io/pull/11515
https://github.com/istio/istio.io/pull/11532

### CODE REVIEW

**Comment by craigbox** [comment]
/ok-to-test

Thank you and welcome!

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
Hi saltbo,

I'm updating the CNCF gitdm repository for affilations.  Are you being paid to work on Istio, and if so who can I credit it to?  The CNCF have "Golang资深研发工程北京得到信息科技有限公司" as your affiliation.

Thanks!

**Comment by saltbo** [comment]
Hello, the affiliation you got is out of date. I am currently working in "Li Auto Inc"

**Comment by craigbox** [comment]
If you would like to update it, please send a PR against this file: https://github.com/cncf/gitdm/blob/master/developers_affiliations6.txt#L8277

**Comment by saltbo** [comment]
thanks, PR commited: https://github.com/cncf/gitdm/pull/1346

**Pull request merged**
