### PR TITLE
Update teams.yaml

### PR DESCRIPTION
**Pull request by SkyfireFrancisZ**
adding pmerrison as RM and creating 1.17 RM section

### CODE REVIEW

**Comment by ericvn** [comment]
I think the issue here is pmerrison is not a member of the Istio committee (which he should have been for 3 months by https://github.com/istio/istio/wiki/release-manager-expectations.

**Comment by kfaseela** [comment]
please resolve the conflicts in the file

**Comment by kfaseela** [comment]
@ericvn @howardjohn @linsun approve?

**Review by ericvn — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
Discussed during Combined WG call to have @pmerrison get a PR merged to become member. That was merged in another PR and fixes the test failure here (RMs need to be a member).

**Pull request merged**
