### PR TITLE
Requesting to add arijitvt as member.

### PR DESCRIPTION
**Pull request by arijitvt**
## I want to join the Istio org!

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)
- [x] I have written my company name or "Individual", if not affliated with a company, here: "Individual"
- [x] I have provided a link to at least one PR that I have successfully pushed to one of the Istio repos, [here](https://github.com/istio/istio.io/pull/14111)

### CODE REVIEW

**Comment by craigbox** [comment]
You need to move it one line down to fix the sort order!

**Comment by arijitvt** [comment]
> You need to move it one line down to fix the sort order!

@craigbox 
I was getting this on my macbook, 
```
mylappyt@achattopadh5[org](add/arijit)cat members.yaml  |  cut -d' ' -f2 | grep -B 2 -A 2 arijitvt
angaluri
antonioberben
arijitvt
Arhell
arkodg

```

**Comment by arijitvt** [comment]
> Yes, but H comes before I:
> 
> ```
> Arhell
> arijitvt
> ```

Yeah, I think the cap A in the `Arhell` is confusing the sort utility. Anyways, I fixed that.

**Review by craigbox — APPROVED** [review]

**Pull request merged**
