### PR TITLE
add lin's info for steering nomination

### PR DESCRIPTION
**Pull request by linsun**
See PR for details, let me know if anything should be updated. thanks!

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by linsun** [comment]
I will close the PR as I can't get email addr fixed with multiple commits.

**Comment by craigbox** [comment]
Mastery of the CLA bot is an undocumented requirement for steering membership 🤣😉

**Comment by kebe7jun** [comment]
I'm sorry, I accidentally deleted your branch while browsing PR on my phone.
😂

**Comment by linsun** [comment]
No worries, it can be deleted now :)

**Pull request closed without merging**
