### PR TITLE
add litong01 as environment maintainer

### PR DESCRIPTION
**Pull request by litong01**
Signed-off-by: Tong Li <litong01@us.ibm.com>

I've been working on both operator and user experience components and participated in TOC, environment and user experience working group meetings (Now the combined working group meeting) and contributed to components in docs, operator, user experiences and tests. Love to be a maintainer to take on more work.

The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:
IBM
Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

https://github.com/istio/istio/pull/37849
https://github.com/istio/istio/pull/37684
https://github.com/istio/istio/pull/37505
https://github.com/istio/istio/pull/37058
https://github.com/istio/istio/pull/35731
https://github.com/istio/istio/pull/35666
https://github.com/istio/istio/pull/35666
https://github.com/istio/istio/pull/35208
https://github.com/istio/istio/pull/35044
https://github.com/istio/istio/pull/34892
https://github.com/istio/istio/pull/32358
https://github.com/istio/istio/pull/31797

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
@istio/wg-environments-maintainers

**Review by jacob-delgado — APPROVED** [review]
@Monkeyanator and @costinm and myself have approved this

**Comment by craigbox** [comment]
Welcome!

**Review by craigbox — APPROVED** [review]

**Comment by litong01** [comment]
@craigbox @howardjohn @jacob-delgado Thanks so much! Very happy to be here with the team and all great people of istio community.

**Pull request merged**
