### PR TITLE
Update TOC membership and admin roles

### PR DESCRIPTION
**Pull request by nrjpoddar**
- Removed Dan Berg for TOC List
- Removed Dan Berg from admin roles
- Kept Dan Berg in developer role

The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [ ] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [ ] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [ ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [ ] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [ ] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

### CODE REVIEW

**Comment by nrjpoddar** [comment]
Updated the TOC/admin list as per Steering guidelines.

cc @craigbox @ssuchter

@craigbox the admins-for-istio.md seems to be outdated for admins for Slack, Twitter, Google Drive. Mind taking a look and refreshing the list? Secondly, I don't have slack admin rights, so can you remove Dan Berg as admin?

cc @dcberg

**Comment by hzxuzhonghu** [comment]
Maybe we should add a doc, thanks to previous TOC  members.  CNCF has this way https://github.com/cncf/toc/blob/main/EMERITUS.md

**Comment by nrjpoddar** [comment]
> Maybe we should add a doc, thanks to previous TOC members. CNCF has this way https://github.com/cncf/toc/blob/main/EMERITUS.md

That's a great idea. I can add an Emeritus section.

**Review by howardjohn — APPROVED** [review]

**Review by smawson — APPROVED** [review]

**Review by nrjpoddar — COMMENTED** [review]
@smawson can you remove Dan from Istio's slack admin group?

**Comment by smawson** [comment]
> @smawson can you remove Dan from Istio's slack admin group?

I think only @louiscryan can do that, he's the primary owner on slack.

**Comment by louiscryan** [comment]
Done

**Pull request merged**
