### PR TITLE
Add carolyn and xinnan to T&R WG

### PR DESCRIPTION
**Pull request by carolynhu**
If you are joining the org, please fill out the template below:

- [x ] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [ x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x ] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x ] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

List your company name, or indicate Individual if you're not affiliated with a company: google

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos: istio/tools repo maintainer

### CODE REVIEW

**Comment by mandarjog** [comment]
Please update the PR title to indicate you are adding your self as a maintainer.
Since the WG is discontinued, we should not add to it really.
That said I want you and @richardwxn  to be added as maintainers on the tools repo, and this seems to be correctly scoped list.

**Comment by carolynhu** [comment]
yeah, thanks for your comment, where should I add it to make me and @richardwxn as the tools repo maintainer? In T&R maintainer list or which one?

cc @richardwxn

**Comment by mandarjog** [comment]
We are not adding names to code owners directly.
Let’s add both to test and release which has the right permissions.

**Comment by mandarjog** [comment]
@carolynhu please update the title of the PR to
“Adding Carolyn and xinnan as maintainers Of test and release”

**Comment by carolynhu** [comment]
@mandarjog I think add us as members would be okay to get the right permissions, so I added the handles under members field.

**Comment by ericvn** [comment]
I will add this to this week's T&R WG to get lead approvals.

**Comment by carolynhu** [comment]
@ericvn any update on this thread?

**Comment by mandarjog** [comment]
@ericvn both Carolyn and Xinnan meet the requirements. They have a lot of code in the tools repo, and they should be able to approve that code now.

**Comment by ericvn** [comment]
@smawson I'm not sure why this PR was merged. At this point, I don't see any approvals from any of the T&R WG leads.

**Comment by linsun** [comment]
I know this is already approved but wanted to loop in BTR leads to make sure they approve.  The maintainers for each WG needs to be approved by the leads.  @ericvn @fpesce @brian-avery

**Comment by smawson** [comment]
Yes, sorry, @ericvn please review and approve, or if you don't approve lets revert.

**Comment by ericvn** [comment]
@fpesce @brian-avery and I approve this PR (I can't mark it approved). Welcome to the WG Carolyn and Xinnan.

**Comment by mandarjog** [comment]
Thanks @ericvn @fpesce and @brian-avery !

**Pull request merged**
