### PR TITLE
Add costinm and howardjohn as Security maintainers

### PR DESCRIPTION
**Pull request by howardjohn**
As discussed with @lizan @liminw and @duderino 

cc @costinm

### CODE REVIEW

**Comment by duderino** [comment]
CC @myidpt 

We had a thread about this over slack - @liminw and @lizan approved, but I'm not sure @myidpt saw it

**Comment by rshriram** [comment]
LGTM for me!

**Comment by hzxuzhonghu** [comment]
lgtm, we need more reviewers from security wg

**Comment by linsun** [comment]
LGTM

**Review by lizan — APPROVED** [review]

**Comment by ramaraochavali** [comment]
LGTM

**Comment by myidpt** [comment]
> CC @myidpt
> 
> We had a thread about this over slack - @liminw and @lizan approved, but I'm not sure @myidpt saw it

LGTM

**Pull request merged**
