### PR TITLE
add lyzhang1999 as a member

### PR DESCRIPTION
**Pull request by lyzhang1999**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:
[istio/istio#25346](https://github.com/istio/istio/pull/25346#event-3529088298)

### CODE REVIEW

**Comment by craigbox** [comment]
Please update the commit to add your name in alphabetical order.  Thanks!

**Comment by lyzhang1999** [comment]
> Please update the commit to add your name in alphabetical order. Thanks!

done

**Comment by craigbox** [comment]
not according to [the diff](https://github.com/istio/community/pull/451/files/679f1c9f2fea580169177a551536f3040c72e72c..42f39d6d78b780818757d756b83bac2106e190f8) ?

**Comment by lyzhang1999** [comment]
> not according to [the diff](https://github.com/istio/community/pull/451/files/679f1c9f2fea580169177a551536f3040c72e72c..42f39d6d78b780818757d756b83bac2106e190f8) ?

so sorry, I have got some problem, now please check again

**Review by craigbox — APPROVED** [review]

**Pull request merged**
