### PR TITLE
add ryantking as a developer

### PR DESCRIPTION
**Pull request by ryantking**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:
Solo.io

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:
https://github.com/istio/istio/pull/33359

### CODE REVIEW

**Comment by craigbox** [comment]
Was member not enough for what you wanted to achieve? 

@brian-avery who is working to remove the difference (and knows what it is)

**Comment by ryantking** [comment]
@craigbox Correct, it looks like I need to be a dev in order to close the relevant issue for the work I'm doing

CC: @linsun

**Comment by brian-avery** [comment]
@craigbox just opened the PR :) https://github.com/istio/community/pull/592/files

**Comment by ryantking** [comment]
@craigbox Great! Closing this then

**Pull request closed without merging**
