### PR TITLE
add member: osswangxining to community members

### PR DESCRIPTION
**Pull request by osswangxining**
## I want to join the Istio org!

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)
- [x] I have written my company name or "Individual", if not affliated with a company, here: Alibaba Cloud
- [x] I have provided a link to at least one PR that I have successfully pushed to one of the Istio repos, here: [A multi-cluster node authorizer to support multi-cluster scenario in ambient mesh istio#49011](https://github.com/istio/istio/pull/49011)

### CODE REVIEW

**Review by kfaseela — APPROVED** [review]

**Comment by kfaseela** [comment]
Hi @osswangxining : I just realized that you have given a link to a commit by @delavet to add yourself as author. Was it a copy paste mistake, could you please edit the description and add your own commit? If not, I will have to revert this PR

**Comment by osswangxining** [comment]
> * A multi-cluster node authorizer to support multi-cluster scenario in ambient mesh istio#49011

Hi @kfaseela , sorry for late response because of long public vacation.  For this PR feature, I contributed as coauthor as you can get the info from the design doc as below. Not sure if this is ok or not?

Please refer to https://docs.google.com/document/d/10uf4EvUVif4xGeCYQydaKh9Yaz9wpysao7gyLewJY2Q/edit?resourcekey=0-6i9VYHbp91h6Avy6syu_oA#heading=h.xw1gqgyqs5b for more details.

**Comment by kfaseela** [comment]
Hello @osswangxining , as per https://github.com/istio/community/blob/master/ROLES.md a PR authored by self is required to be a member, along with some other criteria as well.. We are so happy to have your design contributions, and it would be great if you could make a GitHub contribution as well, as the goal is to be more familiar with the Istio GitHub related activities to showcase commitment to continuous contribution to the project in the future. I am sure, making one PR wouldn't be a big deal for you 🙂

**Pull request merged**
