### PR TITLE
WORKING-GROUPS.md: Add Jackie Maertens (Elliott) to PSWG

### PR DESCRIPTION
**Pull request by justinpettit**
Replace Greg Hanson with Jackie Maertens (Elliott) on PSWG.

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
LGTM

**Comment by keithmattix** [comment]
No arguments from me: is there a teams.yaml file change needed?

**Comment by justinpettit** [comment]
> No arguments from me: is there a teams.yaml file change needed?

Good catch.  I'll prepare a PR right now.

**Comment by craigbox** [comment]
Your PR wasn't from a fork so I can't edit it to resolve this for you, sorry.
(#1513 got in first by the looks.)

**Comment by justinpettit** [comment]
I can't see how to rebase through GitHub's site, so I created PR #1516 with git CLI tools to replace it.  I'll drop this one.  Sorry about the noise.

**Pull request closed without merging**
