### PR TITLE
Add zhihanz to org and developers

### PR DESCRIPTION
**Pull request by ZhiHanZ**
If you are joining the org, please fill out the template below:

- [x]  I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)

- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

List your company name, or indicate Individual if you're not affiliated with a company:
Google
Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos:
https://github.com/istio/istio/pull/26255

### CODE REVIEW

**Comment by louiscryan** [comment]
Welcome!

Once you've met the 'one PR' requirement I'm happy to approve. In the meantime work with your mentor if you need issues assigned to you or help with code reviews.

**Comment by ZhiHanZ** [comment]
> Welcome!
> 
> Once you've met the 'one PR' requirement I'm happy to approve. In the meantime work with your mentor if you need issues assigned to you or help with code reviews.

I have made a PR in previous week location is
https://github.com/istio/istio/pull/26255

**Comment by craigbox** [comment]
Thanks for updating - the PR was approved, and so you should be good to go from TOC's perspective once you've fixed your conflicts.  (The files have been reorganised since your commit.)

**Comment by linsun** [comment]
@ZhiHanZ please rebase before we approve, thanks!

**Pull request closed without merging**
