### PR TITLE
Add chaodaig to WG - Test and Release Maintainers/Operations

### PR DESCRIPTION
**Pull request by chaodaiG**
Already joined istio in #414 , this PR is for joining the WG for managing prow as oncall

### CODE REVIEW

**Comment by linsun** [comment]
@istio/wg-test-and-release-maintainers-operations @istio/wg-test-and-release-maintainers leads - please indicate your approval for this before steering approves this.

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
@linsun Part of the reason we moved the operations part of the T&R group to a sub team (and maybe we should have moved it elsewhere), is that the T&R WG Leads for the most part don't know who is being added/removed from the operations team. This left the T&R team having to approve PRs as people were being added/removed that we did not know. And they typically never would show up in WG meetings.

I assume from John's approval he knows this person and vouches that they should be added.

**Comment by cjwagner** [comment]
Having `WG - Test and Release Maintainers/Operations` as a sub-team has resulted in a lot of email spam for me and I haven't found a good way to filter it. Can we move or replace the team with one that is not a sub-team? I don't see much benefit from a sub-team here given that references to the parent teams are rarely applicable to the operations team.

**Comment by ericvn** [comment]
@howardjohn Thoughts on making operations their own team? Would this imply they have to be their own WG? I don't know that we want to add that additional work.

**Comment by howardjohn** [comment]
I think we can make the team split without a new WG. The github org and the
"logical" WG setup doesn't need to 1:1 align?

**Comment by ericvn** [comment]
I created #442 in response to the comments above. I don't know enough about GH mail to confirm that all these changes will reduce the email. I create a non WG named group and moved these members into it. Once it's merged, we can update CODEOWNERS in test-infra to use the new group and delete the subgroup. Hopefully, this will solve the issues.

**Comment by ericvn** [comment]
I believe once https://github.com/istio/test-infra/pull/2935 is merged @chaodaiG should have access as desired.

**Comment by chaodaiG** [comment]
Great! Thank you @ericvn 

/close

**Pull request closed without merging**
