### PR TITLE
Apply for membership

### PR DESCRIPTION
**Pull request by yyyhhhh**
## I want to join the Istio org!

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)
- [x] I have written my company name or "Individual", if not affliated with a company, here: DaoCloud
- [x] I have provided a link to at least one PR that I have successfully pushed to one of the Istio repos, here: [_____https://github.com/istio/istio.io/pull/13984_____]

### CODE REVIEW

**Review by kfaseela — APPROVED** [review]
/ok-to-test

**Comment by kfaseela** [comment]
Could you please fix the Google cla error?

**Comment by ericvn** [comment]
> Could you please fix the Google cla error?

Faseela, the Google CLA is old and no longer required (note that there is no required to the right of it). The EasyCLA which is now used does pass (and is required).

Need to check with @craigbox to see about getting that actually removed.

**Comment by ericvn** [comment]
Looks like @therealmitchconnors got the test removed from the list..

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
