### PR TITLE
add lizan as security WG co-lead

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by louiscryan** [comment]
note that this would make you a lead in two WGs which is not common practice.

**Comment by linsun** [comment]
I raised the same point too at the last TOC mtg.

**Comment by lizan** [comment]
@louiscryan @linsun It is already discussed and approved in 3/6 TOC per meeting notes. Mandar is leading two as well.

**Comment by louiscryan** [comment]
Fair point!

I approve - thanks for being willing to do the heavy lifting etc.

**Pull request merged**
