### PR TITLE
Add pmerrison to PSWG

### PR DESCRIPTION
**Pull request by pmerrison**
Add pmerrison to PSWG as Tetrate's representative

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by craigbox** [comment]
Looks like you also need to be an Istio member, which you're not currently?

**Comment by ericvn** [comment]
@pmerrison should be able to satisfy the member requirements (usually gated on the PR). Just need to add them back in above.

**Comment by pmerrison** [comment]
> Looks like you also need to be an Istio member, which you're not currently?

Hmm, I thought I already was, I'm L302 of https://github.com/istio/community/blob/master/org/members.yaml#LL302C1-L302C1.  Is there somewhere else @ericvn ?

**Comment by craigbox** [comment]
--- FAIL: TestConvertedOrg (0.01s)
    config_test.go:111: team maintainer not in top level: [pmerrison]

Sorry, it seems it wants you to become a general "Maintainer" before you can become a specific "Product Security Maintainer".

Try adding yourself at Line 62 also.

**Comment by pmerrison** [comment]
Fixed.  Thanks @craigbox

**Review by craigbox — APPROVED** [review]
if it LGT Zhonghu it LGT me

**Pull request merged**
