### PR TITLE
Updated TOC list to reflect current members

### PR DESCRIPTION
**Pull request by nrjpoddar**
The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [ ] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [ ] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [ ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [ ] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [ ] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

### CODE REVIEW

**Comment by nrjpoddar** [comment]
I grep'ed for `rshiram's` GitHub handle to see if there are permissions we need to switch, and this is what I got:

```bash
ADMINS-FOR-ISTIO.md:9:| [CircleCi](https://circleci.com) | Secondary CI system | [rshriram](https://github.com/rshriram), [linsun](https://github.com/linsun), [louiscryan](https://github.com/louiscryan), [smawson](https://github.com/smawson)
ADMINS-FOR-ISTIO.md:10:| [Discourse](https://discuss.istio.io) | Discussion forums | [askmeegs](https://github.com/askmeegs), [linsun](https://github.com/linsun), [oaktowner](https://github.com/oaktowner), [rshriram](https://github.com/rshriram)
ADMINS-FOR-ISTIO.md:11:| [Docker Hub](https://hub.docker.com) | Container registry | [rshriram](https://github.com/rshriram), [costinm](https://github.com/costinm), [mandarjog](https://github.com/mandarjog), [vadimeisenbergibm](https://github.com/vadimeisenbergibm), [frankbu](https://github.com/frankbu)
ADMINS-FOR-ISTIO.md:12:| [GitHub](https://github.com/istio) | Source control, bug tracking | [howardjohn](https://github.com/howardjohn), [rshriram](https://github.com/rshriram), [linsun](https://github.com/linsun), [louiscryan](https://github.com/louiscryan), [smawson](https://github.com/smawson)
ADMINS-FOR-ISTIO.md:17:| [Google Custom Search Engine](https://cse.google.com/cse/) | Search engine for *istio.io | [jasonall](https://github.com/jasonall), [rshriram](https://github.com/rshriram)
ADMINS-FOR-ISTIO.md:23:| [Shared Google Drive](https://drive.google.com/corp/drive/u/0/folders/0AIS5p3eW9BCtUk9PVA) | Design document storage | [rshriram](https://github.com/rshriram), [linsun](https://github.com/linsun), [louiscryan](https://github.com/louiscryan), [smawson](https://github.com/smawson), [jasminejaksic](https://github.com/jasminejaksic)
org/developers.yaml:159:- rshriram
org/teams.yaml:56:      - rshriram
org/teams.yaml:160:          - rshriram
org/teams.yaml:179:              - rshriram
org/teams.yaml:189:              - rshriram
org/teams.yaml:323:      - rshriram
org/teams.yaml:421:      - rshriram
org/teams.yaml:461:      - rshriram
steering/elections/2020/VOTERS.md:148:- rshriram
```

@howardjohn I can remove or replace his roles on other files if you can help me. I'm not sure if ADMINS_FOR-ISTIO.md is for enforcement or documentation or both.

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
Only org/ is used in automation, rest is just docs. The org one should mostly just be WG membership - I think he is welcome to stay a member if he wants? Not sure if he intention left himself there, I saw he was removed from admins

**Comment by nrjpoddar** [comment]
> Only org/ is used in automation, rest is just docs. The org one should mostly just be WG membership - I think he is welcome to stay a member if he wants? Not sure if he intention left himself there, I saw he was removed from admins

So I'm assuming someone in the ADMIN list will do the required work for removing Shriram as needed. Definitely keeping him in member/developer list seems appropriate.

**Review by linsun — APPROVED** [review]

**Comment by linsun** [comment]
I think Shriram pretty much removed himself from many things last week.  We can remove additional things as he wishes.

**Pull request merged**
