### PR TITLE
Adding myself to the contributor list

### PR DESCRIPTION
**Pull request by pramodrj07**
github username - pramodrj07

The most common reason to send a PR to this repository is to join the Istio org.  If you are joining, please fill out this template.  If you are not, please **delete all the below**.

- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://slack.istio.io)

List your company name, or indicate Individual if you're not affiliated with a company:

Company name - vmware

Provide a link to at least one PR that you have successfully pushed to one of the Istio repos:

I have not yet pushed PRs into the official istio repo, but have used istio significantly in other open source projects. I am looking forward to contribute more to the source code of istio from now.
1. https://wiki.onap.org/pages/viewpage.action?pageId=79202667
2. https://wiki.onap.org/display/DW/Deploying+ONAP4K8s+with+ISTIO+service+mesh

### CODE REVIEW

**Comment by smawson** [comment]
Can you fill out the last two parts of the template?

1) What is your affiliation

2) Any PRs that you've pushed to an Istio repo

**Comment by pramodrj07** [comment]
> Can you fill out the last two parts of the template?
> 
> 1. What is your affiliation
> 2. Any PRs that you've pushed to an Istio repo

I have added and updated the details to the template Sven.

**Comment by smawson** [comment]
Please get at least one PR committed to an Istio repo and then update this PR.

**Comment by pramodrj07** [comment]
> Please get at least one PR committed to an Istio repo and then update this PR.

Thanks Sven. I shall do that and get back

**Comment by rvennam** [comment]
Please reopen after meeting the PR requirement.

**Pull request closed without merging**
