### PR TITLE
Update WORKING-GROUPS.md

### PR DESCRIPTION
**Pull request by wenchenglu**
adding Tao to the security leads

### CODE REVIEW

**Comment by wenchenglu** [comment]
@geeknoid 
@wattli

**Comment by wenchenglu** [comment]
No problem. I think this change reflects the current level of leadership in Istio security group. Please help bring this up in steering committee meeting and we can wait after the approval to merge this PR. It is not urgent.

**Comment by geeknoid** [comment]
I'll add this to the agenda for our next meeting.

Thanks.

**Comment by ldemailly** [comment]
should #22 be reverted then (or this one also provisionally merged)

**Comment by geeknoid** [comment]
I should have noted the need for approval from the committee for that
previous PR. I think it's fine to leave it there for now, we can remove it
if there's an issue.

**Pull request closed without merging**
