### PR TITLE
details on how to add training and certification providers

### PR DESCRIPTION
**Pull request by kfaseela**
Required for  https://github.com/istio/istio.io/pull/15238

Similar to https://kubernetes.io/training/

### CODE REVIEW

**Review by linsun — COMMENTED** [review]
LGTM

will leave open for others to review

**Review by keithmattix — COMMENTED** [review]
LGTM

**Comment by justinpettit** [comment]
LGTM

**Comment by craigbox** [comment]
suggest you remove duplication:

```
## Promote your company on istio.io

If your company supports Istio, you can list it on our [Ecosystem](https://istio.io/latest/about/ecosystem/)
or [Training and Certification](https://istio.io/latest/about/training/) pages.
Under Ecosystem, we have categories for *providers* (who offer hosted or managed Istio services
to their customers), *professional services* (who offer implementation support
or consulting for Istio) and *integrations* (commercial or open source products
that work with Istio).

To add an entry to either page, edit [data/companies.yml](https://github.com/istio/istio.io/blob/master/data/companies.yml)
and add your information in the `providers`, `pro_services`, `integrations`, `training` or `certification`
section, as appropriate. Please add your company logo, preferably in SVG
format, to [static/logos](https://github.com/istio/istio.io/blob/master/static/logos).

The Istio steering committee reserves the right to remove logos of companies that
are not demeed to be in good standing in the community.
```

**Comment by kfaseela** [comment]
> suggest you remove duplication:
> 
> ```
> ## Promote your company on istio.io
> 
> If your company supports Istio, you can list it on our [Ecosystem](https://istio.io/latest/about/ecosystem/)
> or [Training and Certification](https://istio.io/latest/about/training/) pages.
> Under Ecosystem, we have categories for *providers* (who offer hosted or managed Istio services
> to their customers), *professional services* (who offer implementation support
> or consulting for Istio) and *integrations* (commercial or open source products
> that work with Istio).
> 
> To add an entry to either page, edit [data/companies.yml](https://github.com/istio/istio.io/blob/master/data/companies.yml)
> and add your information in the `providers`, `pro_services`, `integrations`, `training` or `certification`
> section, as appropriate. Please add your company logo, preferably in SVG
> format, to [static/logos](https://github.com/istio/istio.io/blob/master/static/logos).
> 
> The Istio steering committee reserves the right to remove logos of companies that
> are not demeed to be in good standing in the community.
> ```

Fixed

**Review by craigbox — APPROVED** [review]

**Pull request merged**
